---
- name: checking SSH connection
  hosts: test_vms
  user: centos
  gather_facts: False
  tasks:
    - name: check ssh to remote hosts
      register: ssh_connection_test
      shell: "hostname; id"
    - debug:
        msg: "SSH_CONNECTION SUCCESS!"
      when: ssh_connection_test is success
    - debug:
        msg: "SSH_CONNECTION FAILED!"
      when: ssh_connection_test is unreachable    